-- ============================================================================
-- Pluvite - estrutura necessaria para o ecossistema de alertas
-- Rode no SQL Editor do Supabase (painel > SQL Editor > New query).
-- Todos os comandos sao idempotentes: pode rodar mais de uma vez.
-- ============================================================================

-- 1. Tabela de alertas em tempo real (ja existe no projeto; aqui apenas
--    garantimos as colunas usadas pelos 3 canais).
create table if not exists public.alertas_tempo_real (
  id           bigint generated by default as identity primary key,
  tipo         text        not null,
  prioridade   text        not null default 'MEDIA',
  municipio    text,
  endereco     text,
  descricao    text,
  statusatual  text        not null default 'Ativo',
  criado_em    timestamptz not null default now()
);

alter table public.alertas_tempo_real add column if not exists endereco    text;
alter table public.alertas_tempo_real add column if not exists statusatual text default 'Ativo';
alter table public.alertas_tempo_real add column if not exists criado_em   timestamptz default now();

create index if not exists idx_alertas_criado_em
  on public.alertas_tempo_real (criado_em desc);


-- 2. Dispositivos mobile registrados para push notification.
--    O app envia o Expo Push Token no primeiro acesso (POST /api/dispositivos).
create table if not exists public.dispositivos (
  id            bigint generated by default as identity primary key,
  auth_id       uuid,
  push_token    text        not null unique,
  plataforma    text        not null default 'android',
  municipio     text,
  ativo         boolean     not null default true,
  atualizado_em timestamptz not null default now()
);

create index if not exists idx_dispositivos_municipio
  on public.dispositivos (municipio) where ativo;


-- 3. Cidade do cidadao: usada para direcionar o WhatsApp so para o municipio
--    afetado. (A coluna telefone ja existe.)
alter table public.cidadao add column if not exists cidade text;


-- 4. Permissoes
--    O backend Python usa a chave do .env. Se estiver usando a chave anon,
--    as policies abaixo liberam o que o servico precisa.
alter table public.alertas_tempo_real enable row level security;
alter table public.dispositivos       enable row level security;

drop policy if exists "alertas_leitura_publica" on public.alertas_tempo_real;
create policy "alertas_leitura_publica"
  on public.alertas_tempo_real for select
  using (true);

drop policy if exists "alertas_insercao_servico" on public.alertas_tempo_real;
create policy "alertas_insercao_servico"
  on public.alertas_tempo_real for insert
  with check (true);

drop policy if exists "dispositivos_upsert_proprio" on public.dispositivos;
create policy "dispositivos_upsert_proprio"
  on public.dispositivos for all
  using (true) with check (true);
